version: "2"
services:

  redis:
    image: redis:4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      internal-net: 

  rabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    networks:
      internal-net: 

  airports:
    build:
      context: airports
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
    networks:
      internal-net: 

  trips:
    build:
      context: trips
    depends_on:
      - rabbit
    environment:
        REDIS_HOST: "redis"
        REDIS_PORT: "6379"
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
    networks:
      internal-net: 

  gateway:
    build:
      context: gateway
    depends_on:
      - rabbit
    ports:
        - "8000:8000"
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        AIRPORTS_HEALTH_CHECK: http://airports:8000/health
        TRIPS_HEALTH_CHECK: http://trips:8000/health
    networks:
      internal-net: 
      default: 

volumes:
  redis-data:

networks:
  internal-net: 
    internal: true